import os
import time
from markdown_it import MarkdownIt
import json
from datetime import datetime

IGNORE = "X_" # dessa kataloger och filer ignoreras i AUTO

mdit = MarkdownIt('commonmark', {'breaks':True,'html':True}).enable('table')
news = []

with open("settings.json","r") as f:
	settings = json.loads(f.read())
	ROOT = settings['patches']['ROOT']

def done(a,b):
	if settings['All']: return False
	if not os.path.exists(b): return False
	return os.path.getmtime(a) <= os.path.getmtime(b)
def title(s): return s.replace('.md','').replace('_',' ')

def patch(s):
	patches = settings['patches']
	for key in patches:
		s = s.replace(key,patches[key])
	return s

def wrapHtml(original, filename, t, level, content=""):
	print('wrapHtml',original)
	t = title(t)
	index = 1 + filename.rindex("/")
	short_md = filename[index:].replace('.html','.md')
	long_md = filename.replace('.html','.md')

	res = [
		f"<!-- Generated by makeAll.py 1.0 from {original} -->",
		'<html>',
		'	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />',
		'	<head>',
		f'		<title>{t}</title>',
		# '		<link rel="icon" type="image/x-icon" href="favicon.ico">',
		'		<meta charset = "utf-8"/>'
	]
	for i in reversed(range(level)):
		res.append('		<link href="' + i * '../' + 'style.css" rel="stylesheet" type="text/css" >')
	res.append('	</head>')
	res.append('<body>')

	if level == 1:
		res.append('<table>')
		res.append('<tr class=vinjett height=100px><td>')
		res.append('<a href="../Seniorschack_Stockholm/Xperiment/F%C3%B6redrag/Lewis_Chess_Men/">')
		res.append("<img height=100px src=" + (level-1) * '../' + "X_bilder/knight2.png ></a>")
		res.append("</td><td class=vinjett>Seniorschack Stockholm</td></tr>")
		res.append('</table>')
	else:
		if os.path.exists(long_md):
			res += [f'<h1><a href="{short_md}">{t}</a> </h1>']
		else:
			res += [f'<h1>{t}</h1>']

	res += [content,'</body>','</html>']

	with open(filename, 'w', encoding='utf8') as g:
		s = '\n'.join(res)
		g.write(s)
		print('AUTO',filename)

def noExt(s):
	s = s.replace("_", " ")
	if settings['showExt']: return s
	else:
		p = s.rindex('.')
		if p: return s[:p]
		return s

def getLink(f):
	with open(f,encoding='utf8') as f1:
		link = f1.read().strip()
		return patch(link)

def makeMenu(href,title): return [title, href]

def transpileDir(directory, level=0):
	global news
	if type(directory) is str:
		path = directory
		name = directory
		nyheter = False
		dokument = False 
	else:
		path = directory.path
		name = directory.name
		nyheter = path.endswith('\\Nyheter') 
		dokument = path.endswith('\\Dokument')

	if name.endswith('.css'): return

	name = name.replace("_", " ")

	hash_html = []
	hash_link = []
	hash_directory = []
	hash_others = []

	indexHtml = ""

	for f in os.scandir(path):
		if os.path.isfile(f) and f.name.endswith('.md'):
			if f.name == 'index.md':
				if done(f.path,f.path.replace('.md','.html')): continue
				indexHtml = writeMD(f.path)
			else:
				if done(f.path,f.path.replace('.md','.html')): continue
				html = writeMD(f.path)
				if html:
					filename = f.path.replace('.md', '.html').replace('\\', '/')
					wrapHtml('markdown ' + f.path, filename, f.name, level + 1, html)

	for f in os.scandir(path):
		if os.path.isfile(f):
			if f.name.endswith('.md'): pass
			elif f.name.endswith('.html'): hash_html.append(f)
			elif f.name.endswith('.link'): hash_link.append(f)
			elif f.name not in ['favicon.ico','style.css']:
				if not f.name.startswith(IGNORE): hash_others.append(f)
		else:
			print('f.name',f.name)
			if not f.name.startswith(IGNORE): hash_directory.append(f)

	res = [[noExt(f.name), f.name] for f in hash_html if f.name != 'index.html'] 
	res += [[noExt(f.name),getLink(f.path)] for f in hash_link] 
	res += [[noExt(f.name), f.name] for f in hash_others] 
	for f in hash_directory: 
		res += [[f.name.replace("_", " "), f.name]]
		transpileDir(f, level + 1)

	res.sort()
	if nyheter or dokument: res.reverse()

	res = [f"\t<tr><td><a href='{href}'>{title.replace('_',' ')}</a></td></tr>" for [title,href] in res if title != "Nyheter"]
	res = "<table>\n" + "\n".join(res) + "\n</table>"
	if nyheter: news = res

	if level == 0: 
		res += f'<div style="font-size:16px">{str(datetime.now())[:16]}</div>'
		res += news

	indexHtml = res if indexHtml == "" else indexHtml.replace("AUTO",res)
	if indexHtml: wrapHtml('directory ' + name, path + '/index.html', name, level+1, indexHtml)

def writeMD(long):
	with open(long,encoding='utf8') as f:
		md = f.read()
		print('MD',long)
		html = mdit.render(md)
		html = patch(html)
	return html

start = time.time_ns()
transpileDir(ROOT)
print(round((time.time_ns() - start)/10**6),'ms')
print()
